### ISSUE TITLE
Simplification proposal

### ISSUE THREAD

**Issue by gasche** [reactorlabs/sourir#104]
Here would be a proposal for a great simplification:

- move `const x` to mutable `var x` as suggested, only bound in the
  lexical environment (no heap allocation, no aliasing, no `&x`).

- remove `mut x` and let people use 1-arrays instead when they want an
  aliasing semantics. Only use the heap to allocate arrays
  (as previously proposed, an array *value* is `array a` where `a` is
  a heap adress to a sequence of values).

- require that each variable has a single definition in each segment

I can live with that.

**Comment by o-** [comment]
> remove mut x and let people use 1-arrays instead

😺

**Comment by o-** [comment]
I like how you formalized the proposal I wanted to and I formalized the one you wanted to.

This is very close to what I planned to implement (minus the great idea of removing mut). Should I run with the implementation or are you working on it?

**Comment by gasche** [comment]
Feel free to go ahead and implement. But maybe we could try to merge arrays first, given that they impact the design?

**Comment by gasche** [comment]
I realize now that in the other PR you suggested to sort out variables first and only merge arrays later. I'm fine with either. The current array PR is easy to change to get a by-reference semantics as I previously proposed, which is the one we need to replace `mut`. Doing this after a "great simplification" PR would be a bit more work because of conflicts, but I'm fine with dealing with the conflicts.

**Comment by o-** [comment]
On 05/03/2017 07:23 PM, Gabriel Scherer wrote:
> I realize now that in the other PR you suggested to sort out variables first and only merge arrays later. I'm fine with either. The current array PR is easy to change to get a by-reference semantics as I previously proposed, which is the one we need to replace `mut`. Doing this after a "great simplification" PR would be a bit more work because of conflicts, but I'm fine with dealing with the conflicts.

it's ok. Go ahead and merge the arrays if you all are happy. It's one
thing less dangling! Probably less headache this way round.

**Comment by mhyee** [comment]
Yeah, just merge something first because there's too many proposals in flight right now.

Anyway, I like this proposal. It seemed a bit weird to me at first, but it makes sense to keep non-array variables on the stack/registers/not-heap, and arrays on the heap.

Minor comment about aesthetics: can we declare arrays with `arr a` so it's only three letters, to match with `var x`?

**Comment by mhyee** [comment]
Fixed by #121.

**Comment by mhyee** [comment]
Re-opening this. We implemented the simplification, but we haven't done the third part yet:

> require that each variable has a single definition in each segment

**Comment by gasche** [comment]
I intentionally forgot about this.

**Comment by mhyee** [comment]
This is now done by #140.
