### ISSUE TITLE
Allowing literals as arguments to primitive ops

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/sourir#14]
Right now you can't do

```
x == 1
```

Instead, you have to write 

```
const one = 1
x == one
```

**Comment by gasche** [comment]
For the record, my idea at first was that this constraint was good. Remember, the idea is that `mut` variable correspond to long-lived variables that we do awful things with, while `const` are more like short-lived temporaries (stack slots in a stack machine, registers in an assembly, SSA variables, etc.) used to put complex expressions in A-normal form. For a compiler output it seemed fitting to have to materialize immediates as constant names before using them (well I guess I'm a RISC person), but I agree that on usage it is getting tiresome so I will change this.

**Comment by o-** [comment]
mips has a $zero register. We can think of our machine having infinitly many numbered constant registers which are named after literals :)

**Comment by gasche** [comment]
Fixed by #23.
