### ISSUE TITLE
[Semantics] Invalidate landing pad missing declarations

### ISSUE THREAD

**Issue by o-** [reactorlabs/sourir#21]
I ran into a bit of a stupid cornercase with our invalidate when
reducing the number of captured variables.

Consider the following program:

     mut x = true
     mut r = 1
     branch x l1 l2
    l1:
     r <- 2
     goto c
    l2:
     r <- 3
    c:
     print r

If I prune the false branch we get:

     mut x = true
     mut r = 1
     invalidate (x == y) %deopt_l2 []
     r <- 2
     print r
     stop
     #Landing pad for deopt %deopt_l2
    %deopt_l2:
     r <- 3
     print r

``r`` is not live at line 3 therefore it's not captured. But on line 9 we
perform an update of an undeclared variable (ie. the variable is not
live but its declaration is assumed to be in scope -- its only
half-dead). So far this did not show since we always captured all
variables in scope.

How shall we fix it? Some options i can think of:

* We could allow declaration without initialization and then either add
a declaration prologue to the landing pad or extend invalidate with a
list of declared but not defined variables.

* We say an update requires the old value -- thereby artificially
inflate the liveness interval and unnecessarily capture its value too.

* We patch the landing pad, rewriting update into declaration.

* Something else?

**Comment by janvitek** [comment]
Declaration without init.

**Comment by gasche** [comment]
I think that having declarations without initialization is a good idea: having the mandatory initializer also makes `read x` a bit awkward (`mut x = 0; read x`, meh). But I think that the correct solution here is rather to consider that the variable `r` is (at least half) "live" and should be saved by invalidation. I think of mutable variables as the "costly" variables (declaring one is an allocation, the creation of a stack slot, whatever; or you may think of them as objects with get/set methods), there is no optimization need to partition their liveness interval, and re-declaring them may be slow.

**Comment by o-** [comment]
@gasche I am not sure if I understand your argument. if an invalidate extends the liveness of dead variables then that is certainly a problem from the compilers pov and will prevent numerous optimizations if you reuse variable names in different parts of the program. I really think the invalidate should just capture their declaration but not their value! But this has to be explicit. How about extending the invalidate with another argument:

invalidate expression label captured_values_list captured_declarations_list

**Comment by gasche** [comment]
At a high level, the way I think of invalidate is that the payload should explain how to take the lexical environment (as a proxy for the interpreter state) of the invalidate-from site and transform it into the lexical environment of the invalidate-to site. Our current discussion shows that (1) this vision is a bit simplistic, we also have to extend the lexical environment of the invalidate-to site (at least with the current branch-pruning strategy, but think in general as well) and (2) the details of how to do it from the current instruction payload are not that simple.
