### ISSUE TITLE
[semantics] shadowing

### ISSUE THREAD

**Issue by o-** [reactorlabs/sourir#24]
currently this is a valid sourir program:

    mut x = 1
    mut x = 2
    print x

is this good/bad?

I am asking since this (+ plus the fact that we are not ssa) its kind of a big pain for code motion.

**Comment by gasche** [comment]
I think that supporting shadowing in a language is good in general, but that it is not the point here. If that is a source of trouble, I agree that we can/should forbid shadowing.
