### ISSUE TITLE
osr variable declarations: separate rebinding and redeclaration

### ISSUE THREAD

**Issue by gasche** [reactorlabs/sourir#48]
In #45 we discussed the syntax of osr redeclaration zone, and I made a proposal that is a bit more complex/ambitious (but also more regular and, I think, a bit nicer) than what is currently supported:

> We could do a clear distinction between renamings and new declarations (in terms of the existing scope). We could for example have x <- y, which requires that both variables be of the same mutability class (what you call "type"), and then the general declaration forms const x = e, mut x = e and mut y, that are understood to declare new variables.

@o- answered with common sense and minimalism:

> yeah, this might be interesting in the future. But for all we need osr now it's very easy to get back to the non-allocating version by not having expressions for mutable variables.

If/when we have time (or someone wants to scratch and itch), it might be interesting to try to do the more complete version.

**Comment by mhyee** [comment]
Note: the discussion is actually [here](https://github.com/reactorlabs/sourir/pull/46#discussion_r100071371), in #46.

**Comment by mhyee** [comment]
Fixed by #91.
