### ISSUE TITLE
Codemotion: sink the lifted declaration from mutable to constant variable

### ISSUE THREAD

**Issue by gasche** [reactorlabs/sourir#61]
See the discussions in [#58](https://github.com/reactorlabs/sourir/pull/58#issuecomment-281386063): the code-motion optimization currently creates a fresh *mutable* variable, it would be nicer to create a *constant* variable instead. This should be a relatively easy task, feel free to give it a try if you want to play with the implementation -- and to ask any question here!

The reason why this makes sense / is useful is that, in the imaginary performance model of the language, mutable declarations/assigment "cost more" than constants, as constants are intended to model short-lived stack slots (in a stack VM) of registers (in a register VM), while mutable variables invoke an indirection through the heap.

**Comment by mhyee** [comment]
The basic plan:
- For all mutable declarations, wherever it is in scope, see if it gets modified.
- If not, it can be changed to a `const` declaration
- (i.e. if none of the "requires" are assignments)
- For now, we don't have functions. When we do, it becomes more difficult to reason, e.g. passing a mutable variable into a function, does it get modified?

@o- suggests looking at `hoist_assignment` in [transform](https://github.com/reactorlabs/sourir/blob/master/transform.ml), which does something very similar (in terms of looking at uses of variables). But ultimately, I think I'll put it in a separate function.

**Comment by mhyee** [comment]
A motivating example: apply branch pruning (to eliminate an assignment), this allows a mutable declaration to be converted to const, then we can apply constant propagation.

**Comment by mhyee** [comment]
Fixed by #91.
