### ISSUE TITLE
OsrMut should take an expr, not a var

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/sourir#69]
https://github.com/reactorlabs/sourir/blob/master/instr.ml#L49

We want:
```ocaml
and osr_def =
  | OsrConst of variable * expression
  | OsrMut of variable * expression (* This was variable *)
  | OsrMutUndef of variable
```

There was probably a reason why it wasn't like this, but we should investigate.

**Comment by gasche** [comment]
I think that this is #48. We want to have both variable renaming and new declarations/creations, but it is important to distinguish them as separate operations.
